"""empty message

Revision ID: 0840d614162b
Revises: None
Create Date: 2015-12-30 14:18:41.692963

"""

# revision identifiers, used by Alembic.
revision = '0840d614162b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.create_index(op.f('ix_autonomous_system_asn'), 'autonomous_system', ['asn'], unique=False)
    op.add_column('prefix', sa.Column('version', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prefix_id'), 'prefix', ['id'], unique=False)
    op.create_unique_constraint(None, 'prefix', ['prefix'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prefix', type_='unique')
    op.drop_index(op.f('ix_prefix_id'), table_name='prefix')
    op.drop_column('prefix', 'version')
    op.drop_index(op.f('ix_autonomous_system_asn'), table_name='autonomous_system')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
